### ISSUE TITLE
Python 3.8 support

### ISSUE THREAD

**Issue by k-mamak** [kennyhml/pyinterception#13]
Could we possibly consider adding support for Python 3.8? Given that I'm using Windows 7 and, according to the official Python website, Python versions 3.9 and later are incompatible with Windows 7 or earlier versions, I believe Python 3.8 support would be highly beneficial.

**Comment by CanberkGunduz** [comment]
I am experiencing the same issue right now, did you find a workaround?

**Comment by k-mamak** [comment]
yes I did. do you still need help?

**Comment by CanberkGunduz** [comment]
I found out your repo for the 3.8 support (Thank you soo much for doing it and sharing). But I still have an issue with the arrow keys, press("down") yields 2, press("up") yields 8 just like a numpad. I couldnt find how to just use down arrow with press. Do you know a solution for that?

**Comment by CanberkGunduz** [comment]
No, thank you very much!!

**Comment by 0xTTAN** [comment]
@CanberkGunduz @k-mamak I would appreciate some help, guys. Win7 x64 user here.

**Comment by CanberkGunduz** [comment]
k-mamak has his own fork of interception called [pyinterception3.8support](https://github.com/k-mamak/pyinterception3.8support). If you download that and from your current projects directory in the terminal do the following "pip install your_directory\pyinterception3.8support". Then Interception should work as intended.

**Comment by kennyhml** [comment]
@0xTTAN it will work. I just wanted to make sure you know it's not a recent version so there may be bugs.
