### ISSUE TITLE
How to listen to mouse buttons？

### ISSUE THREAD

**Issue by Egrt** [kennyhml/pyinterception#14]
May I ask how to monitor whether the left mouse button is pressed or the side mouse button is pressed? I look forward to your reply。

**Comment by kennyhml** [comment]
@Egrt sorry for the late reply, I somehow have notifications for issues on this repo turned off. I really need to fix that.

You can see examples for what youre trying to achieve in [here](https://github.com/kennyhml/pyinterception/blob/f8a6f58861368972def63790939d5dd0bd5be483/src/interception/inputs.py#L277)
