### ISSUE TITLE
How do listen to the key?

### ISSUE THREAD

**Issue by Luciener** [kennyhml/pyinterception#16]
Hello.
How do listen to the 'a' key being pressed to start the function?
Or just remake the function "_listen_to_events" to the necessary button?

(Offtop)
In my opinion the misspell in "inpyts.py" Line 325 
	print("No longer intercepting mouse events.")
maybe:
	print("No longer intercepting keyboard events.")

**Comment by kennyhml** [comment]
Whoops thats probably cause I just copy pasted the entire thing and didnt adjust some part.


Yea you could do something similar to the `_listen_to_events` function, however youre going to have to mutli-thread it.

For **capturing** keystrokes id recommend you just use pynputs `keyboard.Listener`
