### ISSUE TITLE
How to track simultaneous pressing of two keys?

### ISSUE THREAD

**Issue by Luciener** [kennyhml/pyinterception#18]
Hello.
How to implement a listener of two simultaneously pressed keys? (Shift + f1)

(I use exactly Interception, since the Pynput and BoppreH keyboards do not work when the application is open)
(BoppreH:   https://github.com/boppreh/keyboard)

I've tried such options, but I don't understand how to catch simultaneous keystrokes (in file "inputs.py"):
Code:

`

def _listen_to_events(context: Interception, stop_button: str) -> None:

    stop = _get_keycode(stop_button)
    try:
        while True:
            device = context.wait()
            stroke = context.receive(device)

            if context.is_keyboard(device) and stroke.code == stop:
                return

            # Shift + f1.
            if (context.is_keyboard(device)
                    and stroke.code == 42
                    and stroke.code == 59):
                print("11111 (---not)")

            if (context.is_keyboard(device)
                    and stroke.code == 42):
                print("22222 (Worked)")
                if (stroke.code == 59):
                    print("33333 (---not)")

            if (context.is_keyboard(device)
                    and stroke.code == 59):
                print("44444 (Worked)")

            if (stroke.code == 42 and stroke.code == 59):
                print("55555 (---not)")

            print(f"Received stroke {stroke} on mouse device {device}")
            context.send(device, stroke)
    finally:
        context.destroy()
`

**Comment by kennyhml** [comment]
So, `shift` in the combination `Shift + F1` would commonly be referred to as the **modifier** of the keypress.

As far as Im concerned, interception does not provide a modifier flag, I would recommend you use other libraries such as pynput which do indeed support the modifier.

Your mistake is looking for two keypresses, you dont want to do that. You want to look for F1 and then check whether the modifier shift is given.

Alternatively. if you really want to keep it pyinterception only, you could just remember somewhere which key was pressed last, and if current key is F1 and last key is shift, then thatll do.

**Comment by Luciener** [comment]
Thanks. 
Other keyboards are not suitable due to the fact that they are all blocking by the application. Interception lacks this drawback.

**Comment by Luciener** [comment]
Can you tell me what "state" and "information" are? Couldn't figure out how these values are created. 
Perhaps they can be controlled.

`Received stroke KeyStroke(code=59, state=0, information=0) on mouse device 0`

**Comment by kennyhml** [comment]
You can find what the `state` flag tells you in the `_consts.py` file, tldr it just lets you know whether the key was pushed down or released, as they are seperate events.

What `information` is im not sure either, typically this would be flags of the input such as windows api sent inputs having a 0x10  (16) flag that tells the receiving application the input was sent through the windows api

**Comment by Luciener** [comment]
Thanks.
I am just wondering.
In the program, the `KEYBOARD_MAPPING parameter "f1": 0x70` convert to "code=42". 
But real if take "HEX" number "0x70" and convert  to "DEC", obtained another digit = 112.
And all other numbers are also converted to other values. Why?

**Comment by kennyhml** [comment]
So this is a more complicated question, 0x70 is the **virtual key code** of the key, however what we are passing and returning in the `code` parameter you are looking at is the **scan code**.

in `_keycodes.py`, if you scroll to the bottom you will see the following:
```py
for c in range(32, 128):
    KEYBOARD_MAPPING[chr(c).lower()] = windll.user32.VkKeyScanA(wintypes.WCHAR(chr(c)))

for k, v in KEYBOARD_MAPPING.items():
    KEYBOARD_MAPPING[k] = windll.user32.MapVirtualKeyA(divmod(v, 0x100)[1], 0)
```
The first for-loop overrides all characters that are typically keyboard layout dependent, as you know there is QWERTZ layouts or QWERTY layout or AZERTY etc.

The second loop replaces all of the virtual key codes with their scan code, after this step the values in the dictionary you are seeing dont at all represent the value they will end up having at runtime.

This approach is preferred over hardcoding the scan codes because I can dynamically acquire them by asking the OS and thus support dynamic keyboard layouts.
