### ISSUE TITLE
mouse control without a physical mouse

### ISSUE THREAD

**Issue by Emre-Kahveci** [kennyhml/pyinterception#19]
I'm not sure if this is a problem or not, so I tried to reach out in another way via private message, but I couldn't find a channel to send a private message.

I made a mouse automation system with interception and was hoping to use it on my 2nd computer (a minicomputer) but my minicomputer doesn't have a keyboard and mouse. Is there any way to send mouse and keyboard input with pyinterception when a mouse and keyboard are not plugged in?

**Comment by kennyhml** [comment]
Im honestly not sure if its possible, lol.
Try to use the auto capture, it will try each number and see if something comes through or not.

**Comment by Emre-Kahveci** [comment]
When I tested with the "identify.exe" application in the samples folder in interception-driver, I could not see the clicks I made with remote control. But I don't want to record with capture and then play that recording, the mouse movements I will make are the movements specified in python code

like `interception.click(100, 100)`

**Comment by kennyhml** [comment]
your remote software will relay your inputs to the host computer using inputs sent via your operating systems API, they will not be part of the input stream which interception watches so its no surprise that they dont show up.

Like I said, call `interception.auto_capture_devices` and see whether it determines a working device number.

**Comment by Emre-Kahveci** [comment]
did not work in the code I tried using interception.auto_capture_devices

the code where I try to move the mouse

```
import interception

interception.auto_capture_devices(keyboard=True, mouse=True)
interception.move_relative(100, 100)
```

Is there a method I can use other than this method?

**Comment by kennyhml** [comment]
No. If that doesnt work youre gonna have to plug in a physical input device (which makes sense since thats what interception hooks)
