### ISSUE TITLE
Combined Device Feature Request - Keyboard Device Not Detected!

### ISSUE THREAD

**Issue by mhawash** [kennyhml/pyinterception#20]
I have tried it on Windows 11 on my HP laptop, where all of the detected keyboard keys are captured as a mouse device... so if there is a way to assign the captured mouse device as the keyboard device as well, that would be a lot helpful in such cases. 

Thanks a lot for your hard work, really appreciate it.

**Comment by kennyhml** [comment]
This would just require another argument to pass to the capture process I guess, should be a fairly trivial change to make yourself for now, but I will keep it in mind.
