### ISSUE TITLE
auto_capture_devices fails from listener desync

### ISSUE THREAD

**Issue by necr0potenc3** [kennyhml/pyinterception#27]
https://github.com/kennyhml/pyinterception/blob/32002c590d0ae6947b625e30b26dbc27aaa2e5fd/src/interception/inputs.py#L381C1-L381C25

auto_capture_devices function needs a "time.sleep(0.1)" after "listener.start()" or it might fail in some occasions.

**Comment by kennyhml** [comment]
Sorry for the late reply, ive been pretty busy.

Are you sure about that? I am personally unable to reproduce the issue.

I distribute projects using this library to a fair share of people and none of them ever had issues with the auto-capture either.
