### ISSUE TITLE
Keyboard and mouse may fail in set_devices

### ISSUE THREAD

**Issue by necr0potenc3** [kennyhml/pyinterception#28]
https://github.com/kennyhml/pyinterception/blob/32002c590d0ae6947b625e30b26dbc27aaa2e5fd/src/interception/inputs.py#L402

set_devices should be altered to:
interception.keyboard = keyboard if keyboard is not None else interception.keyboard
interception.mouse = mouse if mouse is not None else interception.mouse

Current release (not the one on github) fails when keyboard is zero. I understand that mouse should not be zero (10 or greater) but it's more pythonic this way.

**Comment by kennyhml** [comment]
Altered the function to 
```py
@requires_driver
def set_devices(keyboard: Optional[int] = None, mouse: Optional[int] = None) -> None:
    """Sets the devices on the current context. Keyboard devices should be from 0 to 10
    and mouse devices from 10 to 20 (both non-inclusive).

    If a device out of range is passed, the context will raise a `ValueError`.
    """
    if keyboard is not None:
        interception.keyboard = keyboard

    if mouse is not None:
        interception.mouse = mouse
```
As it is overall easier to follow and I'm not really a fan of assignments where no assignment was neccessary afterall.
