### ISSUE TITLE
key detection

### ISSUE THREAD

**Issue by dvdco** [kennyhml/pyinterception#4]
is there a way to detect if an key is pressed without blocking the program? similar to this
`
while True:
    if mouse_left_is_clicked:
        break
    time.sleep(0.1)
`

**Comment by dvdco** [comment]
while True:
    if mouse_left_is_clicked: 
        break
    else:
        time.sleep(0.1)

**Comment by kennyhml** [comment]
Hey @dvdco,

no, this library offers no such feature. If you need this to be part of whatever youre doing it suggest you use another module for it.
