### ISSUE TITLE
sending keystrokes to inactive window

### ISSUE THREAD

**Issue by zinkq** [kennyhml/pyinterception#7]
Hi!

I assume that the library doesn't provide sending keystrokes to an inactive window. 
Do you have any idea how can I perform that? You know - any tips, any ideas?
It would really simplify my work, tho.

**Comment by kennyhml** [comment]
Hey again.

It's not really possible to "send keystrokes to an inactive window", you can cheat it a little by setting said window active using windows api calls for the duration of the input.

You can hear more about this here https://youtu.be/J3fatZ2OVIU
